### ISSUE TITLE
最终得到的关键点数据异常

### ISSUE THREAD

**Issue by liuyi999111** [flyingzhao/mxnet_VanillaCNN#1]
你好，我通过您的博客一步步编译了mxnet 在android 上的lib，然后转换了一些检测人脸关键点的caffe模型，但是最后输出的数据会出现负数，VanillaCNN也是这样，能请教一下错误可能会出在哪里吗？

**Comment by flyingzhao** [comment]
你可以读一下我的代码，可能是其中某些细节被你忽略了，建议你实际的跑一下我的程序。

**Comment by liuyi999111** [comment]
我跑了一下你的python 代码，在预测的时候报错了


<img width="1077" alt="error" src="https://cloud.githubusercontent.com/assets/13236407/21448529/c9cdd4fa-c91e-11e6-9d35-56cf300ea627.png">

同样的我在手机上也遇到了这个问题，但是如果我用自己编译的 android 端的 lib 就不会这个报错。这是应为我的 mxnet 的问题吗？

你的出现在使用mxnet 预测之前用了 caffe 来预测。我看到用caffe 得到的结构也有负数...
<img width="1052" alt="caffe" src="https://cloud.githubusercontent.com/assets/13236407/21448701/67fb5a20-c920-11e6-88ad-e891ae494714.png">

**Comment by flyingzhao** [comment]
可能是mxnet编译的问题，你用自己编译的lib试试看。

**Comment by flyingzhao** [comment]
最后的结果需要加上0.5，你仔细看我的代码

 `landmark=(points+0.5)*128`

你能不能把你自己编译不会报错的android的lib发给我看一下，我分析一下是不是lib的问题。

**Comment by liuyi999111** [comment]
非常感谢，我得到了关键点的数据。
[mxnet_predict-all.cc.zip](https://github.com/flyingzhao/mxnet_VanillaCNN/files/670416/mxnet_predict-all.cc.zip)
这个模型在我的手机执行预测需要50ms左右的时间，您还知道有什么方式可以在Android手机上更快的跑CNN吗？你的博客真的太棒了。

**Comment by flyingzhao** [comment]
有没有对应的安卓动态链接库.so

**Comment by flyingzhao** [comment]
在安卓上跑的更快，只能自己魔改了。你可以看看CNNdroid，它用GPU实现的。现在各家框架在安卓上投入的工作不是很多，可以期待一下caffe2go，估计快要开源了，应该会针对移动平台优化。

**Comment by flyingzhao** [comment]
很高兴我的博客能帮到你，欢迎继续关注我的博客。

**Comment by liuyi999111** [comment]
[libmxnet_predict.so.zip](https://github.com/flyingzhao/mxnet_VanillaCNN/files/670424/libmxnet_predict.so.zip)
我尝试过 CNNdroid ，支持的 layer 有限，而且执行效率低得惊人，只有卷积层会试图调用GPU，简单的层就是执行的java代码。

**Comment by flyingzhao** [comment]
我觉得目前这个cnn用于人脸特征点已经是足够小了。比较快的模型我在另一个安卓项目里面有，但是它的模型太大了，将近90M。我看过一些公司的技术分享，他们大多是从底层执行进行优化的，由于我水平有限，目前对底层没什么研究。还有一种方法就是把照片上传到服务器，处理完了再返回到客户端。

**Comment by flyingzhao** [comment]
这个so是能正常工作的吗？我拿自己手机测一下，分析一下原因。

**Comment by liuyi999111** [comment]
是的

**Comment by flyingzhao** [comment]
出错的so文件是哪一个？是从我的github上下载的吗？

**Comment by liuyi999111** [comment]
出错的是 mxnet 推荐的那个 [demo](https://github.com/Leliana/WhatsThis) 的 lib,你的程序出现报错是发生在jupyter notebook 的文件里面。报的错是一样的和 shape 有关

**Comment by flyingzhao** [comment]
也就是说，在android上，你拿自己编译的mxnet的so是可以正常工作的，但是在电脑上我的python程序不能工作？

**Comment by liuyi999111** [comment]
是的

**Comment by flyingzhao** [comment]
` Caused by: org.dmlc.mxnet.MxnetException: [16:16:44] jni/../mxnet_predict-all.cc:18100: Check failed: from.shape() == to->shape() operands shape mismatch`

用你的so在我手机上居然会报错。

**Comment by flyingzhao** [comment]
你电脑ubuntu版本是多少？我在我的14.04上python程序能正常工作的。

**Comment by flyingzhao** [comment]
同样的模型为什么在你手机上能工作，我的就不行呢？

**Comment by liuyi999111** [comment]
我是 mac ， 可能和 ndk 工具有关。

**Comment by flyingzhao** [comment]
都是玄学啊，不过能工作就可以了。我觉得模型应该是没有问题的，可能是mxnet本身的问题，毕竟mxnet的android部分很久没有更新了。
